### ISSUE TITLE
Finish installing and error on first playing the sketch

### ISSUE THREAD

**Issue by rtomas** [necsoft/codepoems#60]
When installing processing-java from Processing 2.X i get this error (sketch not working)
"/usr/bin/processing-java: line 2: /Applications/Processing: No such file or directory"

Later install processing-java from Procesing 3.X and i works ok with this error
"java.lang.RuntimeException: java.lang.ClassNotFoundException: sketch1435848461492
at processing.core.PApplet.runSketch(PApplet.java:10722) at processing.core.PApplet.main(PApplet.java:10534) Caused by: java.lang.ClassNotFoundException: sketch1435848461492 at java.net.URLClassLoader$1.run(URLClassLoader.java:366) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) at processing.core.PApplet.runSketch(PApplet.java:10719) ... 1 more"

**Comment by rtomas** [comment]
Later with processing-java from Procesing 3.X. No more errors and sketch working ok :)

**Comment by necsoft** [comment]
So it doesn't work at all with processing 2x? That's strange...
